### ISSUE TITLE
Chat copy not working

### ISSUE THREAD

**Issue by Shawran** [Skytils/SkytilsMod#261]
There is a thing called copy chat messages. Unlike the Skyblock Extras mod it doesn't copy when you do the command "Ctrl + Click "
Now I don't know that what click it means but every 3 mouse buttons I tried it doesn't work so maybe you fix it in the new update

**Comment by My-Name-Is-Jeff** [comment]
Cannot reproduce

**Comment by Shawran** [comment]
> Cannot reproduce

cannot reproduce what??

**Comment by My-Name-Is-Jeff** [comment]
The issue you are facing with the information provided

> > Cannot reproduce
> 
> cannot reproduce what??
