### ISSUE TITLE
Mana Flux Orb / Maddox Batphone appearing on screen when loading

### ISSUE THREAD

**Issue by Zurxey** [Skytils/SkytilsMod#272]
I'm loading into Skyblock, and automatically getting this appearing on my screen:
![image](https://user-images.githubusercontent.com/22053077/197070289-9bbe25a9-457d-4490-8c02-7fba446181ff.png)

This is what appears in my inventory:
![image](https://user-images.githubusercontent.com/22053077/197070372-b3d59eda-d5d0-4657-b138-69ee384de744.png)

Mods Folder:
![image](https://user-images.githubusercontent.com/22053077/197070434-a65088cb-d799-4231-89ea-cb9c97a954e3.png)

Its both the Mana Flux Orb, and Maddox Batphone.

**Comment by shuuyu** [comment]
Github Issues are intended for contributors only. If you're having issues with this, turn your `Head Size` option down to one in your Skytils configurations and it should go away. If you have any further issues, please use the support channel in the [Discord server](https://discord.gg/skytils).
